### ISSUE TITLE
HTTP loadbalancers & Letsencrypt

### ISSUE THREAD

**Issue by samber** [scaleway/scaleway-cloud-controller-manager#154]
Is it possible to use a letsencrypt certificate with scw load balancer ?

The current certificate annotation only supports certificates uploaded from the console.

**Comment by pablo-ruth** [comment]
Hello @samber, it's possible to reference Letsencrypt certificate created via API, CLI, Terraform or the Console via the annotation, eg:
> service.beta.kubernetes.io/scw-loadbalancer-id: fr-par-1/xxxxxxx-xxxx-xxxxxxxxxx-xxxxxxxxxxxxx
Do you have an error ?

**Comment by samber** [comment]
How would you do that with a load balancer created from kube?

**Comment by samber** [comment]
Sorry if I was not clear.

I'm trying to connect the SCW LB to my deployment, without an intermediary reverse proxy layer.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-fr-par-1
  annotations:
    service.beta.kubernetes.io/scw-loadbalancer-zone: "fr-par-1"
    service.beta.kubernetes.io/scw-loadbalancer-type: "lb-s"
    service.beta.kubernetes.io/scw-loadbalancer-protocol-http: "true"
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
```

Reaching port 80 works perfectly (even if I would like to disable it in the future).  How am I supposed to add the certificate annotation if my letsencrypt certificate is managed by the cert-manager?

Thanks for your help.
