### ISSUE TITLE
LB with externalTrafficPolicy: Local

### ISSUE THREAD

**Issue by LucasBoisserie** [scaleway/scaleway-cloud-controller-manager#62]
When create a service load-balancer with `externalTrafficPolicy: Local` only node with the pod should be added as backend. Currently all nodes are added and there are health check status as failed

```yaml
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 51.159.114.85
  loadBalancerSourceRanges: ...
```

![image](https://user-images.githubusercontent.com/5363260/116218843-3d6ef600-a74b-11eb-8361-6f539c6432f6.png)
